"""create dashboard tables

Revision ID: 133f1353114e
Revises: d18c47712616
Create Date: 2026-07-17 19:06:41.679728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '133f1353114e'
down_revision: Union[str, None] = 'd18c47712616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_schedule',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Identificador único del registro de horario'),
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='Usuario propietario del horario'),
    sa.Column('grupo', sa.String(length=20), nullable=False, comment='Grupo asignado al usuario para la asignatura'),
    sa.Column('clave', sa.String(length=20), nullable=False, comment='Clave de la asignatura'),
    sa.Column('asignatura', sa.String(length=200), nullable=False, comment='Nombre completo de la asignatura'),
    sa.Column('profesor', sa.String(length=200), nullable=False, comment='Nombre del profesor asignado al grupo'),
    sa.Column('lunes', sa.String(length=50), nullable=True, comment='Horario del lunes (ej. 07:00-08:30)'),
    sa.Column('martes', sa.String(length=50), nullable=True, comment='Horario del martes'),
    sa.Column('miercoles', sa.String(length=50), nullable=True, comment='Horario del miércoles'),
    sa.Column('jueves', sa.String(length=50), nullable=True, comment='Horario del jueves'),
    sa.Column('viernes', sa.String(length=50), nullable=True, comment='Horario del viernes'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha y hora de creación del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha y hora de la última actualización'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_current_schedule_user_id'), 'current_schedule', ['user_id'], unique=False)
    op.create_table('curriculum_courses',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Identificador único de la asignatura curricular'),
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='Usuario propietario de la currícula'),
    sa.Column('school', sa.String(length=50), nullable=False, comment='Plantel al que pertenece la currícula (ej. escom, esiatec)'),
    sa.Column('carrera', sa.String(length=100), nullable=False, comment='Carrera a la que pertenece la asignatura'),
    sa.Column('periodo', sa.String(length=20), nullable=False, comment='Periodo curricular recomendado (semestre o etapa)'),
    sa.Column('clave', sa.String(length=20), nullable=False, comment='Clave única de la asignatura dentro del plan de estudios'),
    sa.Column('nombre', sa.String(length=200), nullable=False, comment='Nombre completo de la asignatura'),
    sa.Column('tipo', sa.String(length=50), nullable=True, comment='Tipo de asignatura (Obligatoria, Optativa, etc.)'),
    sa.Column('creditos', sa.String(length=10), nullable=True, comment='Créditos que aporta la asignatura'),
    sa.Column('horas_teoria', sa.String(length=10), nullable=True, comment='Horas de teoría por semana'),
    sa.Column('horas_practica', sa.String(length=10), nullable=True, comment='Horas de práctica por semana'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha y hora de creación del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha y hora de la última actualización'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_courses_user_id'), 'curriculum_courses', ['user_id'], unique=False)
    op.create_index('ix_curriculum_courses_user_school_carrera', 'curriculum_courses', ['user_id', 'school', 'carrera'], unique=False)
    op.create_table('kardex_entries',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Identificador único de la entrada'),
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='Usuario propietario de la entrada'),
    sa.Column('clave', sa.String(length=20), nullable=False, comment='Clave de la asignatura en el SAES'),
    sa.Column('asignatura', sa.String(length=200), nullable=False, comment='Nombre completo de la asignatura'),
    sa.Column('calificacion', sa.String(length=10), nullable=False, comment='Calificación alfanumérica (ej. 10, 9.5, NP, NA)'),
    sa.Column('periodo', sa.String(length=20), nullable=False, comment='Periodo escolar en el que se cursó la asignatura'),
    sa.Column('fecha', sa.String(length=20), nullable=True, comment='Fecha de acreditación reportada por el SAES'),
    sa.Column('forma_evaluacion', sa.String(length=50), nullable=True, comment='Forma de evaluación (ordinario, extraordinario, etc.)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha y hora de creación del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha y hora de la última actualización'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'clave', 'periodo', name='uq_kardex_entries_user_clave_periodo')
    )
    op.create_index(op.f('ix_kardex_entries_user_id'), 'kardex_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kardex_entries_user_id'), table_name='kardex_entries')
    op.drop_table('kardex_entries')
    op.drop_index('ix_curriculum_courses_user_school_carrera', table_name='curriculum_courses')
    op.drop_index(op.f('ix_curriculum_courses_user_id'), table_name='curriculum_courses')
    op.drop_table('curriculum_courses')
    op.drop_index(op.f('ix_current_schedule_user_id'), table_name='current_schedule')
    op.drop_table('current_schedule')
    # ### end Alembic commands ###
