"""create room_occupancy table

Revision ID: 2ff63a665fd0
Revises: d23c571a0f32
Create Date: 2026-07-17 19:27:04.446616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ff63a665fd0'
down_revision: Union[str, None] = 'd23c571a0f32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_occupancy',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Identificador único del registro de ocupación'),
    sa.Column('carrera', sa.String(length=100), nullable=False, comment='Carrera a la que pertenece el grupo'),
    sa.Column('grupo', sa.String(length=20), nullable=False, comment='Nombre o clave del grupo'),
    sa.Column('clave', sa.String(length=20), nullable=False, comment='Clave de la asignatura'),
    sa.Column('asignatura', sa.String(length=200), nullable=False, comment='Nombre de la asignatura'),
    sa.Column('periodo', sa.String(length=50), nullable=False, comment='Periodo escolar del registro'),
    sa.Column('cupo', sa.Integer(), nullable=False, comment='Cupo máximo del grupo'),
    sa.Column('inscritos', sa.Integer(), nullable=False, comment='Cantidad de alumnos inscritos'),
    sa.Column('disponibles', sa.Integer(), nullable=False, comment='Lugares disponibles restantes'),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha y hora en que se obtuvo el dato del SAES'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_room_occupancy_lookup', 'room_occupancy', ['carrera', 'grupo', 'clave'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_room_occupancy_lookup', table_name='room_occupancy')
    op.drop_table('room_occupancy')
    # ### end Alembic commands ###
