"""create_users_table

Revision ID: 711e5f37449f
Revises: 
Create Date: 2026-07-17 00:50:33.410490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '711e5f37449f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Identificador único de la cuenta'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Correo electrónico único del usuario'),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='Hash bcrypt de la contraseña; nulo para cuentas de Google'),
    sa.Column('google_id', sa.String(length=255), nullable=True, comment='Identificador único de Google OAuth'),
    sa.Column('full_name', sa.String(length=200), nullable=True, comment='Nombre completo del usuario'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Indica si la cuenta puede iniciar sesión'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha y hora de creación de la cuenta'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha y hora de la última actualización'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
