"""create saes_credentials table

Revision ID: d18c47712616
Revises: 711e5f37449f
Create Date: 2026-07-17 01:01:14.589895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd18c47712616'
down_revision: Union[str, None] = '711e5f37449f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saes_credentials',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Identificador único de la credencial'),
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='Usuario propietario de la credencial (relación 1:1)'),
    sa.Column('boleta', sa.String(length=20), nullable=False, comment='Boleta del alumno en el SAES'),
    sa.Column('school', sa.String(length=50), nullable=False, comment='Identificador del plantel (ej. escom, esiatec)'),
    sa.Column('encrypted_login', sa.LargeBinary(), nullable=False, comment='Token `login` del SAES cifrado con AES-256-GCM'),
    sa.Column('encrypted_session', sa.LargeBinary(), nullable=False, comment='Token `session` del SAES cifrado con AES-256-GCM'),
    sa.Column('saes_expires_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha de expiración reportada por el SAES'),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True, comment='Fecha de la última sincronización académica exitosa'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha y hora de creación del vínculo'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha y hora de la última actualización'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('boleta'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saes_credentials')
    # ### end Alembic commands ###
