"""create saved schedules and option items tables

Revision ID: d23c571a0f32
Revises: 133f1353114e
Create Date: 2026-07-17 19:19:39.997528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd23c571a0f32'
down_revision: Union[str, None] = '133f1353114e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_schedules',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Identificador único del horario guardado'),
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='Usuario propietario del horario'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Nombre descriptivo del horario'),
    sa.Column('is_favorite', sa.Boolean(), nullable=False, comment='Indica si el horario es favorito'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha y hora de creación'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha y hora de la última actualización'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_schedules_user_id'), 'saved_schedules', ['user_id'], unique=False)
    op.create_table('option_items',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Identificador único del grupo en el horario'),
    sa.Column('schedule_id', sa.Uuid(), nullable=False, comment='Horario guardado al que pertenece'),
    sa.Column('grupo', sa.String(length=20), nullable=False, comment='Grupo asignado'),
    sa.Column('clave', sa.String(length=20), nullable=False, comment='Clave de la asignatura'),
    sa.Column('asignatura', sa.String(length=200), nullable=False, comment='Nombre de la asignatura'),
    sa.Column('profesor', sa.String(length=200), nullable=False, comment='Nombre del profesor'),
    sa.Column('edificio', sa.String(length=100), nullable=True, comment='Edificio donde se imparte la clase'),
    sa.Column('aula', sa.String(length=100), nullable=True, comment='Aula donde se imparte la clase'),
    sa.Column('lunes', sa.String(length=50), nullable=True, comment='Horario del lunes'),
    sa.Column('martes', sa.String(length=50), nullable=True, comment='Horario del martes'),
    sa.Column('miercoles', sa.String(length=50), nullable=True, comment='Horario del miércoles'),
    sa.Column('jueves', sa.String(length=50), nullable=True, comment='Horario del jueves'),
    sa.Column('viernes', sa.String(length=50), nullable=True, comment='Horario del viernes'),
    sa.Column('order_index', sa.Integer(), nullable=False, comment='Orden del grupo dentro del horario'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha y hora de creación'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha y hora de la última actualización'),
    sa.ForeignKeyConstraint(['schedule_id'], ['saved_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_option_items_schedule_id'), 'option_items', ['schedule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_option_items_schedule_id'), table_name='option_items')
    op.drop_table('option_items')
    op.drop_index(op.f('ix_saved_schedules_user_id'), table_name='saved_schedules')
    op.drop_table('saved_schedules')
    # ### end Alembic commands ###
